spring:
  application:
    name: reservation-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;MODE=PostgreSQL
    username: sa
    password: sa
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 30000
      DOG-SERVICE:
        connectTimeout: 1000
        readTimeout: 5000
      OWNER-SERVICE:
        connectTimeout: 1000
        readTimeout: 5000
---
server:
  port: 8300
spring:
  config.activate.on-profile: default
---
server:
  port: 8301
spring:
  config.activate.on-profile: instance2